package com.umeng.soexample.ui.shop.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.umeng.soexample.model.data.GreendaoBean;

import com.umeng.soexample.ui.shop.db.GreendaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greendaoBeanDaoConfig;

    private final GreendaoBeanDao greendaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greendaoBeanDaoConfig = daoConfigMap.get(GreendaoBeanDao.class).clone();
        greendaoBeanDaoConfig.initIdentityScope(type);

        greendaoBeanDao = new GreendaoBeanDao(greendaoBeanDaoConfig, this);

        registerDao(GreendaoBean.class, greendaoBeanDao);
    }
    
    public void clear() {
        greendaoBeanDaoConfig.clearIdentityScope();
    }

    public GreendaoBeanDao getGreendaoBeanDao() {
        return greendaoBeanDao;
    }

}
